-- AlterTable
ALTER TABLE "Interview" ADD COLUMN     "feedback" TEXT,
ALTER COLUMN "score" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "Message" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
